### PR TITLE
export propTypes

### PR DESCRIPTION
**Pull request by Tzelon**
This can help when someone wants to extend Box.

### CODE REVIEW

**Comment by Tzelon** [comment]
thank you:)

**Comment by Monar** [comment]
No problem, but I think this was unnecessary. You always had an access to the `propTypes` via `Box.propTypes` they are `static` property of the `Box` class. 

I'll revert this change during weekend but as it stands for today `v1.0.2` also export `propTypes` 🗡

**Comment by Tzelon** [comment]
Webstorm doesn't give me code completion when using Box.propTypes. 
I know isn't react-styled-box problem but it still nice to have feature.

**Comment by Monar** [comment]
Ok, if this is the reason about then it stays :D

**Pull request merged**
